mysql:
  image: mysql:latest
  volumes:
   - /var/lib/mysql
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=lumen
   - MYSQL_USER=user
   - MYSQL_PASSWORD=password

php:
  build: ./php
  links:
    - mysql:stackmysql
  ports:
   - "9000:9000"
  volumes:
   - ./html/lumen:/srv/http:ro

nginx:
  image: nginx:latest
  links:
    - php:stackphp
    - mysql:stackmysql
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./html/lumen:/usr/share/nginx/html:ro
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf