php:
  build: ./php
  ports:
   - "9000:9000"
  volumes:
   - ./html/lumen:/srv/http:ro

nginx:
  image: nginx:latest
  links:
    - php:stackphp
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./html/lumen:/usr/share/nginx/html:ro
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   # - ./sites/lumen.conf:/etc/nginx/sites-available/lumen.conf
  # command: mkdir /etc/nginx/sites-enabled
  # command: ln -sf /etc/nginx/sites-available/lumen.conf /etc/nginx/sites-enabled/lumen.conf