db:
  image: mysql:latest
  volumes:
   - /var/lib/mysql
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=lumen
   - MYSQL_USER=user
   - MYSQL_PASSWORD=password

phpfpm:
  build: ./php
  links:
    - db:db
  ports:
   - "9000:9000"
  volumes:
   - ./html/lumen:/srv/http

server:
  image: nginx:latest
  links:
    - phpfpm:phpfpm
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./html/lumen:/usr/share/nginx/html
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf