db:
  image: mysql:latest
  container_name: db
  volumes:
   - /var/www/mysql:/var/lib/mysql
  expose:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=lumen
   - MYSQL_USER=user
   - MYSQL_PASSWORD=password

cache:
  image: memcached:latest
  container_name: cache
  expose:
   - "11211:11211"

phpfpm:
  build: ./php
  container_name: phpfpm
  links:
    - db:db
    - cache:cache
  expose:
   - "9000:9000"
  volumes:
   - /var/www/html:/srv/http

server:
  image: nginx:latest
  container_name: server
  links:
    - phpfpm:phpfpm
  ports:
   - "80:80"
  expose:
   - "443:443"
  volumes:
   - /var/www/html:/usr/share/nginx/html
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf